services:
  - type: web
    name: anpr-fastapi
    env: python
    plan: free
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr libtesseract-dev
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=10000
    autoDeploy: true
